### ISSUE TITLE
Project won't compile at the "without AirSim plugin" step

### ISSUE THREAD

**Issue by cbekar** [harvard-edge/airlearning-ue4#1]
Hi,

I have a Windows 10 Pro system with 4.18.3 version of UE4, and just installed VS 17 (15.9.13 version but with Version 15.7.1) compiler toolset. However, the project won't compile after confirming to build the dll. The UE4 building popup appears and then closes immediately. 

In the ss below, you may find the said compiler plugin encircled (sorry about the Turkish wording)
![Building pop up](https://user-images.githubusercontent.com/1816738/59603614-82b74b00-9112-11e9-8361-b431f80e12f0.jpg)

I am new to UE4 projects so do you have any idea on how to workaround this issue, it suggests I might try building it manually. 
![Error window](https://user-images.githubusercontent.com/1816738/59604149-00c82180-9114-11e9-8d4d-cacb86c855e8.PNG)

Thanks for the help. 

Can

**Comment by cbekar** [comment]
In the verbose build window, I have found these logs:
`Discovering modules, targets and source code for project...
ERROR: Windows SDK v8.1 must be installed in order to build this target.
LogSlate: Took 0.000211 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Regular.ttf' (155K)
LogHotReload: Recompiling module MyProject...
LogVSAccessor: Warning: Couldn't access Visual Studio
Candidate modules for hot reload:
  MyProject
Launching UnrealBuildTool... [C:/Program Files/Epic Games/UE_4.18/Engine/Binaries/DotNET/UnrealBuildTool.exe MyProject -Module MyProject Win64 Development -editorrecompile -canskiplink "C:/Users/Can Bekar/Documents/Unreal Projects/MyProject/MyProject.uproject" ]
Performing full C++ include scan (hot reloading a new target)
Creating makefile for hot reloading MyProject (no existing makefile)
Compiling game modules for hot reload
Parsing headers for MyProjectEditor
  Running UnrealHeaderTool "C:\Users\Can Bekar\Documents\Unreal Projects\MyProject\MyProject.uproject" "C:\Users\Can Bekar\Documents\Unreal Projects\MyProject\Intermediate\Build\Win64\MyProjectEditor\Development\MyProjectEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
Reflection code generated for MyProjectEditor in 10.7814074 seconds
ERROR: Windows SDK v8.1 must be installed in order to build this target.`

**Comment by cbekar** [comment]
In the verbose error logs, I have found the following, although it seems that I have already installed Windows 8.1 sdk, it seems that it cannot discover the sdk module. Will reinstall the sdk now. 
[error.txt](https://github.com/harvard-edge/airlearning-ue4/files/3297017/error.txt)

**Comment by srivatsankrishnan** [comment]
Hi Can,
Yes, Windows 8.1 SDK is needed to install the project. It's more of UE4.18 requirement I guess. Thanks for bringing this to our attention. I will update that in our readme.
-Sri

**Comment by srivatsankrishnan** [comment]
@cbekar I tried to uninstall windows 8.1 SDK and I was able to reproduce the error you got. I re-installed windows 8.1 SDK in my visual studio and it seems to compile fine now. I have updated the instruction on the readme. Closing this issue now. Feel free to re-open it if it is not resolved at your end.
-Sri

**Comment by cbekar** [comment]
Thanks Sri, 

I would recommend you to include this walkthrough for smoother installation:
https://docs.unrealengine.com/en-US/Programming/Development/VisualStudioSetup/index.html

Cheers,
Can

**Comment by cbekar** [comment]
Hi all,

After 8.1 SDK installation I am still failing to build the project, this time the logs are like this:
```
LogInit: Warning: Incompatible or missing module: UE4Editor-JsonParsing18Version.dll
Running C:/Program Files/Epic Games/UE_4.18/Engine/Binaries/DotNET/UnrealBuildTool.exe JsonParsing18VersionEditor Development Win64 -project="C:/Users/Can Bekar/Documents/Projects/airlearning/airlearning-ue4/airlearning-ue4/AirLearning.uproject" -editorrecompile -progress -NoHotReloadFromIDE
Using 'git status' to determine working set for adaptive non-unity build.
Creating makefile for JsonParsing18VersionEditor (no existing makefile)
Performing full C++ include scan (no include cache file)
ERROR: Unable to find plugin 'AirSim' (referenced via AirLearning.uproject). Install it and try again, or remove it from the required plugin list.
```
Confirming "build without AirSim plugin" doesn't seem to work.

Kind regards,
Can

**Comment by cbekar** [comment]
Ok just fixed the problem:
airlearning.uproject in the master branch already had the AirSim plugin entry, erasing it was the way to go.

**Comment by cbekar** [comment]
Related issue continues on _building with AirSim plugin_ step. 

After seeing that suggested AirSim version doesn't contain some of the assets (see figure), I've built the master branch for AirSim and then merged the Unreal plugin folders. However it is not sufficient to make the Air Learning project work, and the error log stays the same. 

![image](https://user-images.githubusercontent.com/1816738/59823534-22edb980-9337-11e9-8be4-fc946ff7b82e.png)

[Log file is attached](https://github.com/harvard-edge/airlearning-ue4/files/3308976/AirLearning.log)

**Comment by cbekar** [comment]
I have successfully built the project, without the said assets above, here is a screenshot.

![image](https://user-images.githubusercontent.com/1816738/59825747-88dd3f80-933d-11e9-84df-9aed6a8c04ab.png)

**Comment by srivatsankrishnan** [comment]
Hi Can,
Thanks for pointing out. You are indeed right that there is AirSim plugin defined in the uproject file. I will push the updated uproject file. Good to see you were able to compile the environment generator. As far as the warnings are concerned, they are benign and it should work fine. It just means that it is not able to find those assets in the project. 
-Sri

**Comment by kgpinco** [comment]
> Ok just fixed the problem:
> airlearning.uproject in the master branch already had the AirSim plugin entry, erasing it was the way to go.

Hi,

I am having the same issue and am following your same steps to resolve it.

Please can you explain how to erase this? What's the master branch? 

Thank you,

**Comment by Rutsow** [comment]
> > Ok just fixed the problem:
> > airlearning.uproject in the master branch already had the AirSim plugin entry, erasing it was the way to go.
> 
> Hi,
> 
> I am having the same issue and am following your same steps to resolve it.
> 
> Please can you explain how to erase this? What's the master branch?
> 
> Thank you,

You can open the AirLearning.uproject with notepad. Then delete the part about Airsim plugin.

**Comment by wjh-scut** [comment]
I have deleted the part about Airsim plugin,but still can't solve it.Can someone tell me how to solve this?
![image](https://github.com/harvard-edge/airlearning-ue4/assets/28137201/112ac393-4a6a-4748-8802-f1175f87586f)
