### ISSUE TITLE
Airlearning can compile. Try manually rebuilding from source code

### ISSUE THREAD

**Issue by zhuwenya0000** [harvard-edge/airlearning-ue4#11]
I have followed the instructions in GitHub to complete all the steps, and even installed all the prerequisites, ue4.18 and VS2017, as instructed. However, after moving the airsim plugin folder to the UE-4 folder, when I tried to run airlearning. project, I received an error saying "Airlearning can compile. Try manually rebuilding from source code". airlearning. project generated Airlearning.sln file is runnable. Has anyone encountered and resolved this issue? Thank you very much

**Comment by Menes00** [comment]
how did you solve this your issue? @zhuwenya0000
