### ISSUE TITLE
Airlearning set up in Ubuntu 16.04

### ISSUE THREAD

**Issue by airopti** [harvard-edge/airlearning-ue4#2]
Is it possible to set up Airlearning in Ubuntu 16.04 ? When trying to compile Airlearning by Unreal in Ubuntu 16.04, I met lots of loading mistakes:

- /Game/AI/BP_DynamicAiMeshes : Can't find file for asset. /Game/Dynamic/Balcony_Rail_Double

- /Game/AI/BP_DynamicAiMeshes : Can't find file for asset. /Game/Dynamic/Curtain_02

- /Game/BP/BP_Arena_Meshes : Can't find file for asset. /Game/Dynamic/Balcony_Rail_Double

- /Game/BP/BP_Arena_Meshes : Can't find file for asset. /Game/Dynamic/Curtain_02

- Failed to load /Game/Dynamic/Curtain_02.Curtain_02 Referenced by Default__BP_DynamicAiMeshes_C

- Failed to load /Game/Dynamic/Balcony_Rail_Double.Balcony_Rail_Double Referenced by Mesh_GEN_VARIABLE

- /Game/BP/BP_Cube : Can't find file for asset. /Game/Models/Bed

- /Game/BP/BP_Arena_Meshes : Can't find file for asset. /Game/Models/Bed

- Failed to load /Game/Models/Bed.Bed Referenced by Cube_GEN_VARIABLE

- /Game/AI/BP_AISpawner : Can't find file for asset. /Game/Dynamic/Curtain_02

- /Game/Maps/AirLearning_Arena : Can't find file for asset. /Game/Dynamic/Curtain_02

- Failed to load /Game/Dynamic/Curtain_02.Curtain_02 Referenced by K2Node_SpawnActorFromClass_0

- /Game/Models/Chimney_2 : Can't find file for asset. /Game/ModularNeighborhoodPack/Materials/Brick_01_Inst

- Failed to load /Game/ModularNeighborhoodPack/Materials/Brick_01_Inst.Brick_01_Inst Referenced by Chimney_2

- /Game/Materials/Fir_01_Inst : Can't find file for asset. /Game/ModularNeighborhoodPack/Materials/00_Parent_Foliage_Mat

- /Game/Materials/Fir_01_Inst : Can't find file for asset. /Game/ModularNeighborhoodPack/Textures/Fir_01

- /Game/Materials/Fir_01_Inst : Can't find file for asset. /Game/ModularNeighborhoodPack/Textures/Fir_01_NRM

- /Game/Materials/Fir_01_Inst : Can't find file for asset. /Game/ModularNeighborhoodPack/Textures/Fir_01_SPEC

- Failed to load /Game/ModularNeighborhoodPack/Materials/00_Parent_Foliage_Mat.00_Parent_Foliage_Mat Referenced by Fir_01_Inst

- Failed to load /Game/ModularNeighborhoodPack/Textures/Fir_01.Fir_01 Referenced by Fir_01_Inst

- Failed to load /Game/ModularNeighborhoodPack/Textures/Fir_01_NRM.Fir_01_NRM Referenced by Fir_01_Inst

- Failed to load /Game/ModularNeighborhoodPack/Textures/Fir_01_SPEC.Fir_01_SPEC Referenced by Fir_01_Inst

- /Game/Materials/00_Parent_Foliage_Mat : Can't find file for asset. 

- /Game/ModularNeighborhoodPack/Textures/birch_01

- /Game/Materials/00_Parent_Foliage_Mat : Can't find file for asset. 

- /Game/ModularNeighborhoodPack/Textures/birch_01_NRM

- /Game/Materials/00_Parent_Foliage_Mat : Can't find file for asset. 

- /Game/ModularNeighborhoodPack/Textures/birch_01_SPEC

- Failed to load /Game/ModularNeighborhoodPack/Textures/birch_01.birch_01 Referenced by MaterialExpressionTextureSampleParameter2D_2

- Failed to load /Game/ModularNeighborhoodPack/Textures/birch_01_NRM.birch_01_NRM Referenced by MaterialExpressionTextureSampleParameter2D_3

- Failed to load /Game/ModularNeighborhoodPack/Textures/birch_01_SPEC.birch_01_SPEC Referenced by MaterialExpressionTextureSampleParameter2D_4

Is there anyway to fix these? Thanks so much.

**Comment by srivatsankrishnan** [comment]
Hi, unfortunately, we aren't feature complete on ubuntu yet. If you don't care about the domain randomization in your environment, then its fairly straight forward to get this up and running on ubuntu 16.04. Please email me and I can help you get started with running this on ubuntu. 

The loading error you see is benign and it means these UE4 assets are not available in your project. You can safely ignore them. It doesn't affect the functionality and if you have those assets, these should go away. Some of the assets we used originally are purchased from the UE4 market place and hence can't openly distribute them. But thats why we designed the framework in such a way that depending upon your application, you can import assets/textures and materials specific to that.

**Comment by airopti** [comment]
Thanks so much. Hope Airlearning to be ready for Ubuntu.

**Comment by airopti** [comment]
Dear Srivatsan:


I ignored the environment loading problem in my airlearning project in Ubuntu, and run the airlearning-rl to train the drone by RL. But there was a new problem. As shown in the attachment, it seemed that Airsmi client was connected but no commands were executed by the drone and no training processes. Did I miss some details? Hope for your reply and thank you so much.



------------------ 原始邮件 ------------------
发件人: "Srivatsan Krishnan"<notifications@github.com>;
发送时间: 2019年10月18日(星期五) 凌晨1:40
收件人: "harvard-edge/airlearning-ue4"<airlearning-ue4@noreply.github.com>;
抄送: "Jiansen Huang"<656284564@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [harvard-edge/airlearning-ue4] Airlearning set up in Ubuntu 16.04(#2)




Hi, unfortunately, we aren't feature complete on ubuntu yet. If you don't care about the domain randomization in your environment, then its fairly straight forward to get this up and running on ubuntu 16.04. Please email me and I can help you get started with running this on ubuntu.
 
The loading error you see is benign and it means these UE4 assets are not available in your project. You can safely ignore them. It doesn't affect the functionality and if you have those assets, these should go away. Some of the assets we used originally are purchased from the UE4 market place and hence can't openly distribute them. But thats why we designed the framework in such a way that depending upon your application, you can import assets/textures and materials specific to that.

**Comment by srivatsankrishnan** [comment]
Hi,
I don't see any attachment. But I guess this issue is similar to https://github.com/harvard-edge/airlearning-rl/issues/1. 

After installing the AirSim, you might need to run move.py script available in airlearning-rl repository.  I have updated the instructions now (sorry, I never added that instruction in the first place). We had to change airsim client a little bit to enable domain randomization. If you run the script, I think you should be able to start the training process. If you run into any issue, let me know.

**Comment by airopti** [comment]
Sorry, I met a new problem. Now I can start the RL training process, but the training process will stop unexpected and restart Unreal Engine again. There is an error, "reset error, with cannot reshape array of size 110592 into shape (144,256,4)  error"
![2019-10-22 12-46-00屏幕截图](https://user-images.githubusercontent.com/25297541/67259796-52b9f300-f4ca-11e9-9d32-da05950bbc3b.png)

**Comment by airopti** [comment]
> Sorry, I met a new problem. Now I can start the RL training process, but the training process will stop unexpected and restart Unreal Engine again. There is an error, "reset error, with cannot reshape array of size 110592 into shape (144,256,4) error"
> ![2019-10-22 12-46-00屏幕截图](https://user-images.githubusercontent.com/25297541/67259796-52b9f300-f4ca-11e9-9d32-da05950bbc3b.png)

I rebuilt the AirSmi and now the whole system can work well ~

**Comment by srivatsankrishnan** [comment]
Just so that you know, there is a bug in Airsim (at least the version that we forked) where sometimes you get no response when you request for a state. This can crash the training. So in AirLearning, what we did was to catch the scenario and just restart everything (UE4 etc) and training will start from where it caught that error. This way we can run it for a longer time.
